# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: とりあえずやってみる
tagline: ''
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  技術的な内容とかとりあえずやってみたこと
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mkataigi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mkataigi
github_username: mkataigi

# Build settings
markdown: kramdown
highlighter: pygments
theme: minima
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Permalinks
permalink: pretty

author:
  name: 'Makoto Kataigi'
  url: https://twitter.com/mdo

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/mkataigi
